# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5b5aff2bd57bbc60ed720fb116c9597d516c9cef52ae9a159d52c0b0d3f236b74951c48fc9816a2c62c24273285bb773ec0f058cb2110c13ea1d049a4ab48b9

test:
  secret_key_base: a16d02cb9b2b338654a2c1b39c41dfd7bbfe83261e63b04138d9606c6049d8bb5ec91d3b1247a4e6fe2c07c2c5215e4be505d801496524a12f858fe1addf3e26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
